minimumReleaseAgeExclude:
  - '@toon-format/spec@4.2.0'
  - utilful@3.5.1

shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - vite@5.4.21

packages:
  - docs
  - benchmarks
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
